default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: your-db-name
  password: your-db-password
  host: localhost
  port: 5432
  timeout: 5000

development: 
  <<: *default
  database: rails-bs-admin-starter  
